name: cucumber_pr_merged_monitor

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number with cucumber specs to run agains"
        required: true
        type: string
  pull_request:
    types: [closed]
    branches:
      - 'issue-*'


jobs:
  cucumber_pr_merged_monitor:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'cucumber')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          repository: sublayerapp/crm
          path: crm
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: |
          gem install sublayer octokit jira-ruby
      - name: Run cucumber_pr_merged_monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USERNAME: "scott@sublayer.com"
          JIRA_SITE: "https://sublayer.atlassian.net"
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}

        run: ruby .github/workflows/cucumber_pr_merged_monitor/cucumber_pr_merged_monitor.rb
