name: story_ready_monitor

on:
  workflow_dispatch:

jobs:
  story_ready_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          repository: sublayerapp/crm
          path: crm
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install dependencies
        run: |
          gem install sublayer octokit jira-ruby
      - name: Run story_ready_monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USERNAME: "scott@sublayer.com"
          JIRA_SITE: "https://sublayer.atlassian.net"


        run: ruby crm/.github/workflows/story_ready_monitor/story_ready_monitor.rb
